// The opt-in "Ask" surface (ADR 21). A modal, so it never crowds the tab bar
// and nothing loads until the user opens it. On-device only; answers are
// grounded in the app's data and cite the real cards.

import { useEffect, useRef, useState } from 'preact/hooks';
import { useAssistant, type BaseCorpus } from '../hooks/useAssistant';
import type { GroundingItem } from '../assistant/retrieval';

interface Props {
  open: boolean;
  onClose: () => void;
  corpus: BaseCorpus;
  onGotoCamp: (id: string) => void;
  onGotoArt: (id: string) => void;
  onGotoJournal: () => void;
}

const SUGGESTIONS = [
  'coffee camps',
  'chill lounges to relax',
  'what food is around',
  'my saved camps',
];

export function AskView({ open, onClose, corpus, onGotoCamp, onGotoArt, onGotoJournal }: Props) {
  const a = useAssistant(corpus, open);
  const [q, setQ] = useState('');
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (open) setTimeout(() => inputRef.current?.focus(), 40);
  }, [open]);

  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose(); };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [open, onClose]);

  const submit = (e?: Event) => { e?.preventDefault(); void a.ask(q); };
  const runSuggestion = (s: string) => { setQ(s); void a.ask(s); };

  const gotoItem = (i: GroundingItem) => {
    if (i.kind === 'journal') onGotoJournal();
    else if (i.kind === 'art') onGotoArt(i.id);
    else onGotoCamp(i.campId ?? i.id);      // events navigate to their host camp
    onClose();
  };

  const tierBadge = a.tier === 'builtin'
    ? { label: 'on-device AI', title: "Answers generated by your browser's built-in on-device model." }
    : { label: 'smart search', title: 'No built-in AI model on this browser — showing grounded matches.' };

  return (
    <div
      class={'modal' + (open ? '' : ' modal-hidden')}
      role="dialog" aria-modal="true" aria-labelledby="ask-title"
      onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div class="modal-card">
        <div class="modal-head">
          <h2 id="ask-title">Ask <span class="ask-tier" title={tierBadge.title}>{tierBadge.label}</span></h2>
          <button class="modal-close" type="button" aria-label="Close" onClick={onClose}>✕</button>
        </div>
        <div class="modal-body">
          <form class="ask-form" onSubmit={submit}>
            <input
              ref={inputRef}
              class="ask-input"
              type="search"
              placeholder="Ask about camps, events, food, art…"
              value={q}
              onInput={(e) => setQ((e.target as HTMLInputElement).value)}
            />
            <button class="primary-btn" type="submit" disabled={a.loading}>
              {a.loading ? 'Thinking…' : 'Ask'}
            </button>
          </form>

          <div class="ask-suggestions">
            {SUGGESTIONS.map((s) => (
              <button key={s} type="button" class="ask-chip" onClick={() => runSuggestion(s)}>{s}</button>
            ))}
          </div>

          {a.answer && <p class="ask-answer">{a.answer}</p>}
          {a.facts.length > 0 && !a.answer && (
            <p class="ask-answer">{a.facts.join(' ')}</p>
          )}

          {a.items.length > 0 && (
            <ul class="ask-results">
              {a.items.map((i) => (
                <li key={i.kind + i.id}>
                  <button type="button" class="ask-result" onClick={() => gotoItem(i)}>
                    <span class="ask-result-kind">{i.kind === 'art' ? '🎨' : i.kind === 'event' ? '📅' : i.kind === 'journal' ? '📓' : '🏕'}</span>
                    <span class="ask-result-body">
                      <span class="ask-result-title">
                        {i.faved && <span class="ask-result-star" aria-label="starred">★</span>}
                        {i.title}
                      </span>
                      {i.subtitle && <span class="ask-result-sub">{i.subtitle}</span>}
                    </span>
                  </button>
                </li>
              ))}
            </ul>
          )}

          {a.ready && a.tier !== 'builtin' && (
            <p class="ask-note">
              Conversational answers need a browser with a built-in on-device AI
              model (currently Chrome/Chromium). Here it works as grounded search.
              {a.webgpuDownloadPossible && ' A downloadable on-device model is planned.'}
            </p>
          )}

          <p class="ask-disclaimer">
            Runs entirely on your device — nothing leaves it. Answers come from
            this app's data and can be wrong; tap a result and verify on the
            directory.
          </p>
        </div>
      </div>
    </div>
  );
}
